### ISSUE TITLE
Wont Build for me ?

### ISSUE THREAD

**Issue by geoffw123** [TheCherno/RayTracing#2]
Thanks for providing this for free.

I followed the instructions here, using latest vs 2022

1. Clone recursively: git clone --recursive https://github.com/TheCherno/RayTracing
2. Run scripts/Setup.bat
3. Open RayTracing.sln and hit F5

I cant get the sln to build, get various files not found, not sure if I have missed something or there is a path missing in the sln setup ?

A selection of the errors I get
1>C:\RayTracing\Walnut\vendor\imgui\imgui.h(60,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
2>C:\RayTracing\Walnut\vendor\glfw\include\GLFW\glfw3.h(103,10): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

4>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12,10): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
4>Done building project "RayTracing.vcxproj" -- FAILED.

 Any thoughts on how to fix this would be appreciated, thanks.

**Comment by Soilcsi** [comment]
looks like you didnt installed windows10 sdk. Install it from the Visual Studio Installer.

**Comment by geoffw123** [comment]
Thanks  for the feedback, I had already got Win 10 sdk installed. However after your suggestion I did some more tinkering and managed to fix the problem. If anyone else hits this problem here is what I did

Using the visual studio installer, click on the individual components tab, then right at the bottom you see the Win10 sdk versions available, the middle numbered version was the one ticked originally, I cleared this and then ticked the higher number version and then clicked modify.
Then back in visual studio, right click on the ray tracing project in the solution explorer and click retarget solution, and then select Windows 10 sdk "latest installed version".

The project then rebuilt without errors.

**Comment by geoffw123** [comment]
hiya
Thanks for the reply, I had got the sdk installed but your suggestion was enough for me to fix the problem.
I have written some notes on what i did to fix it in case anyone else hits the problem. I have closed the issue

Thanks again
Geoff

________________________________
