### ISSUE TITLE
Getting error when compiling, something about the input

### ISSUE THREAD

**Issue by ScripterStuff** [TheCherno/RayTracing#5]
I get this error when I try to compile:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: static class Walnut::Application & __cdecl Walnut::Application::Get(void)" (?Get@Application@Walnut@@SAAEAV12@XZ) referenced in function "public: static struct glm::vec<2,float,0> __cdecl Walnut::Input::GetMousePosition(void)" (?GetMousePosition@Input@Walnut@@SA?AU?$vec@$01M$0A@@glm@@XZ)	RayTracing	C:\Users\Student\Documents\SA RayTracing\RayTracing\RayTracing\Walnut.lib(Input.obj)	1	

I don't know what to do, I haven't found anything helpful online either.

**Comment by BenBE** [comment]
This looks like the version of the Walnut source you are linking to your project does not provide the function `?Get@Application@Walnut@@SAAEAV12@XZ` (which would be declared in the source as `public: static class Walnut::Application & __cdecl Walnut::Application::Get(void)`). Please check if the source you are using for Walnut matches with the expected version and that the mentioned function is present there.

You may want to clean your project by removing all cached or previously built binaries to force recompilation. Sometimes such errors appear randomly when files from a previous built are mixed into linking of fresh binaries.

BTW: You can mark things as code by using backticks. That makes such long identifiers much more readable.

**Comment by ScripterStuff** [comment]
Thanks I just needed to update Application.cpp
