### ISSUE TITLE
m_AccumulationData of 'Renderer' class will not initialize to a value of 0

### ISSUE THREAD

**Issue by pan199612** [TheCherno/RayTracing#7]
## Background

In my PC (CPU I5-8400), **debug mode**
m_AccumulationData of 'Renderer' class will not initialize to a value of 0

## Process

The first 'Renderer::OnResize' event is not a problem:
Because the value of 'm_FrameIndex' is 1, 'memset' will be called to initialize
![image](https://user-images.githubusercontent.com/17159985/206890908-940c338a-7560-422e-a6e9-5b57d167f497.png)

The second call to 'Renderer::OnResize' will not call memset because 'm_FrameIndex' is not equal to 1, resulting in 'm_AccumulationData' being all is a negative number:
![image](https://user-images.githubusercontent.com/17159985/206890970-320bd723-dac3-4550-9648-7b6526dc0085.png)

Thanks

**Comment by LilyIsTrans** [comment]
I think I've noticed this problem; everything goes black whenever you resize the window with accumulation turned on. I fixed the issue by adding a call to `ResetFrameIndex()` to the end of `Renderer::OnResize`.
